[[resources]]
name = "sponza-fbx"
url = "https://github.com/acccoco/assets/releases/download/fbx/sponza_0.0.3.zip"
resource_type = "zip"
target_dir = "assets/fbx"
rename_to = "sponza"

[[resources]]
name = "cube-coord-fbx"
url = "https://github.com/acccoco/assets/releases/download/fbx/cube-coord_0.0.1.fbx"
resource_type = "file"
target_dir = "assets/fbx"
rename_to = "cube-coord.fbx"
download_by_default = false

[[resources]]
name = "cornell-box-fbx"
url = "https://github.com/acccoco/assets/releases/download/fbx/cornell-box_0.0.1.fbx"
resource_type = "file"
target_dir = "assets/fbx"
rename_to = "cornell-box.fbx"

[[resources]]
name = "cornell-box-fbx-1"
url = "https://github.com/acccoco/assets/releases/download/fbx/cornell-box_0.0.1.zip"
resource_type = "zip"
target_dir = "assets/fbx"
rename_to = "cornell-box-1"
download_by_default = false

[[resources]]
name = "sponza-fbx-1"
url = "https://github.com/acccoco/assets/releases/download/fbx/sponza-1_0.0.1.zip"
resource_type = "zip"
target_dir = "assets/fbx"
rename_to = "sponza-1"
download_by_default = false

[[resources]]
name = "bistro-gltf"
url = "https://github.com/acccoco/assets/releases/download/fbx/bistro_0.0.1.zip"
resource_type = "zip"
target_dir = "assets/gltf"
rename_to = "bistro"
download_by_default = false

[[resources]]
name = "office-gltf"
url = "https://github.com/acccoco/assets/releases/download/fbx/office_0.0.1.zip"
resource_type = "zip"
target_dir = "assets/gltf"
rename_to = "office"
download_by_default = false

[[resources]]
name = "slang"
url = "https://github.com/shader-slang/slang/releases/download/v2026.11/slang-2026.11-windows-x86_64.zip"
resource_type = "zip"
target_dir = "external"
rename_to = "slang"

[[resources]]
name = "tracy"
url = "https://github.com/wolfpld/tracy/releases/download/v0.13.1/windows-0.13.1.zip"
resource_type = "zip"
target_dir = "external"
rename_to = "tracy"

[[resources]]
name = "streamline"
url = "https://github.com/NVIDIA-RTX/Streamline/releases/download/v2.14.1/streamline-sdk-v2.14.1.zip"
resource_type = "zip"
target_dir = "external"
rename_to = "streamline-sdk"

[[resources]]
name = "nvidia-rtx-gi-repo"
url = "https://github.com/NVIDIA-RTX/RTXGI.git"
resource_type = "git"
target_dir = "external"
rename_to = "rtx-gi"
git_ref = "v2.7.0"
recursive_submodules = true
download_by_default = false

[[resources]]
name = "nvidia-rtx-di-repo"
url = "https://github.com/NVIDIA-RTX/RTXDI.git"
resource_type = "git"
target_dir = "external"
rename_to = "rtx-di"
git_ref = "v3.0.0"
recursive_submodules = true
download_by_default = false

[[resources]]
name = "openpbr-repo"
url = "https://github.com/AcademySoftwareFoundation/OpenPBR.git"
resource_type = "git"
target_dir = "external"
rename_to = "openpbr"
git_ref = "v1.1.1"
recursive_submodules = true
download_by_default = false

[[resources]]
name = "pbrtv4-repo"
url = "https://github.com/mmp/pbrt-v4.git"
resource_type = "git"
target_dir = "external"
rename_to = "pbrtv4"
git_ref = "master"
recursive_submodules = true
download_by_default = false
