# 会被 truvis-path 解析

[[package]]
id = "engine"
entry_root = "engine/shader/entry"
include_roots = ["engine/shader"]
shared_input_roots = ["engine/shader/abi/engine", "engine/shader/lib/engine"]
depends_on = []
output_prefix = "engine"

[[package]]
id = "renderer"
entry_root = "renderer/shader/entry/renderer"
include_roots = ["engine/shader", "renderer/shader"]
shared_input_roots = ["renderer/shader/abi/renderer", "renderer/shader/lib/renderer"]
depends_on = ["engine"]
output_prefix = "renderer"

[[package]]
id = "sample-hello-triangle"
entry_root = "renderer/shader/entry/sample-hello-triangle"
include_roots = ["engine/shader"]
shared_input_roots = []
depends_on = ["engine"]
output_prefix = "samples/hello-triangle"

[[package]]
id = "sample-shader-toy"
entry_root = "renderer/shader/entry/sample-shader-toy"
include_roots = ["renderer/shader"]
shared_input_roots = ["renderer/shader/lib/sample-shader-toy"]
depends_on = []
output_prefix = "samples/shader-toy"
