[package]
name = "shader-toy-app"
version = "0.1.0"
edition = "2024"
description = "ShaderToy standalone application"

[[bin]]
name = "shader-toy"
path = "src/main.rs"

[dependencies]
shader-toy-renderer = { workspace = true }
truvis-render-loop = { workspace = true }
truvis-winit-host = { workspace = true }
truvis-logs = { workspace = true }
truvis-path = { workspace = true }
