[package]
name = "truvis-assimp-binding"
version = "0.1.0"
edition = "2024"
description = "为 Truvis 提供 Assimp C API 绑定"

[package.metadata.truvis_cxx_binding]
native_target = "truvixx-assimp-capi"


[dependencies]


[build-dependencies]
truvis-cxx-binding-codegen = { workspace = true }
truvis-path = { workspace = true }
