[package]
name = "truvis-shader-build"
version = "0.1.0"
edition = "2024"
description = "build shader"


[dependencies]
truvis-logs = { workspace = true }
truvis-path = { workspace = true }
truvis-shader-manifest = { workspace = true }

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

rayon = { workspace = true }
walkdir = { workspace = true }
