[package]
name = "renderer-kit"
version = "0.1.0"
edition = "2024"
description = "App lifecycle contracts, camera/input and renderer-independent CPU state"

[dependencies]
truvis-render-loop = { workspace = true }
truvis-gfx = { workspace = true }
truvis-render-foundation = { workspace = true }
truvis-render-runtime = { workspace = true }

glam = { workspace = true }
log = { workspace = true }
