[package]
name = "shader-toy-renderer"
version = "0.1.0"
edition = "2024"
description = "ShaderToy sample renderer"

[dependencies]
truvis-render-loop = { workspace = true }
renderer-kit = { workspace = true }
renderer-imgui = { workspace = true }
truvis-gfx = { workspace = true }
truvis-render-foundation = { workspace = true }
truvis-render-graph = { workspace = true }
truvis-render-runtime = { workspace = true }
truvis-shader-manifest = { workspace = true }

ash = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
enum-map = { workspace = true }
log = { workspace = true }
