[package]
name = "triangle-app"
version = "0.1.0"
edition = "2024"
description = "Triangle sample standalone application"

[[bin]]
name = "triangle"
path = "src/main.rs"

[dependencies]
triangle-renderer = { workspace = true }
truvis-render-loop = { workspace = true }
truvis-winit-host = { workspace = true }
truvis-logs = { workspace = true }
truvis-path = { workspace = true }
